site_name: Membrane Documentation
site_url: https://membrane-php.github.io
nav:
  - Getting Started: index.md
  - The Basics: basics.md
  - Result: result.md
  - Processors: processors.md
  - Filters: filters.md
  - Validators: validators.md

theme: readthedocs
